public enum SoundType
{
    Walking,
    Running,
    Jumping,
    Landing,
    DoorOpen,
    DoorClose,
    DoorLocked,
    LanternOn,
    LanternOff,
    TubelightAmbience,
    NoteCollect,
    RecordCollect,
    RecordPlace,
    SwitchToggle,
    SurgicalToolCollect,
    ObjectiveComplete,
    Victory,
    Death
}